In [1]:
import os
os.chdir('..')

In [2]:
import torchvision.models as models
import torch as th

In [27]:
m = models.resnet18()
m2 = models.resnet18()

In [38]:
opt = th.optim.SGD(m.parameters(), lr=1)

In [39]:
list(m.parameters())[0][0][0]

tensor([[-0.0188,  0.0291,  0.0100, -0.0325, -0.0388, -0.0210, -0.0065],
        [-0.0100,  0.0159, -0.0004, -0.0146, -0.0291,  0.0292, -0.0062],
        [-0.0060, -0.0073, -0.0380,  0.0093,  0.0159,  0.0171, -0.0119],
        [ 0.0160,  0.0379, -0.0165,  0.0160, -0.0186, -0.0487,  0.0267],
        [ 0.0504, -0.0152, -0.0271, -0.0376, -0.0202, -0.0398, -0.0155],
        [-0.0145, -0.0527, -0.0061, -0.0263, -0.0129, -0.0211, -0.0416],
        [ 0.0306,  0.0424, -0.0471,  0.0049, -0.0421, -0.0093, -0.0077]],
       grad_fn=<SelectBackward>)

In [40]:
list(m2.parameters())[0][0][0]

tensor([[ 0.0447,  0.0180, -0.0344, -0.0346,  0.0099,  0.0022, -0.0163],
        [ 0.0271,  0.0028, -0.0378, -0.0395,  0.0043, -0.0367,  0.0073],
        [-0.0593, -0.0153, -0.0022, -0.0178, -0.0323, -0.0434, -0.0314],
        [ 0.0187,  0.0035, -0.0311,  0.0156,  0.0121,  0.0029, -0.0180],
        [-0.0151,  0.0223, -0.0353, -0.0133, -0.0244,  0.0198,  0.0209],
        [-0.0036, -0.0213, -0.0043,  0.0075,  0.0010, -0.0141, -0.0084],
        [-0.0101, -0.0242,  0.0194,  0.0128,  0.0276, -0.0256, -0.0410]],
       grad_fn=<SelectBackward>)

In [41]:
for p, np in zip(m.parameters(), m2.parameters()):
    p.grad = p - np # because we go to the opposite direction of the gradient

In [42]:
opt.step()

In [43]:
list(m.parameters())[0][0][0]

tensor([[ 0.0447,  0.0180, -0.0344, -0.0346,  0.0099,  0.0022, -0.0163],
        [ 0.0271,  0.0028, -0.0378, -0.0395,  0.0043, -0.0367,  0.0073],
        [-0.0593, -0.0153, -0.0022, -0.0178, -0.0323, -0.0434, -0.0314],
        [ 0.0187,  0.0035, -0.0311,  0.0156,  0.0121,  0.0029, -0.0180],
        [-0.0151,  0.0223, -0.0353, -0.0133, -0.0244,  0.0198,  0.0209],
        [-0.0036, -0.0213, -0.0043,  0.0075,  0.0010, -0.0141, -0.0084],
        [-0.0101, -0.0242,  0.0194,  0.0128,  0.0276, -0.0256, -0.0410]],
       grad_fn=<SelectBackward>)

In [14]:
len(list(m.parameters())), len(m.state_dict().values())

(62, 122)

In [12]:
for p, s in zip(m.parameters(), m.state_dict().values()):
    print(p.shape, s.shape)

torch.Size([64, 3, 7, 7]) torch.Size([64, 3, 7, 7])
torch.Size([64]) torch.Size([64])
torch.Size([64]) torch.Size([64])
torch.Size([64, 64, 3, 3]) torch.Size([64])
torch.Size([64]) torch.Size([64])
torch.Size([64]) torch.Size([])
torch.Size([64, 64, 3, 3]) torch.Size([64, 64, 3, 3])
torch.Size([64]) torch.Size([64])
torch.Size([64]) torch.Size([64])
torch.Size([64, 64, 3, 3]) torch.Size([64])
torch.Size([64]) torch.Size([64])
torch.Size([64]) torch.Size([])
torch.Size([64, 64, 3, 3]) torch.Size([64, 64, 3, 3])
torch.Size([64]) torch.Size([64])
torch.Size([64]) torch.Size([64])
torch.Size([128, 64, 3, 3]) torch.Size([64])
torch.Size([128]) torch.Size([64])
torch.Size([128]) torch.Size([])
torch.Size([128, 128, 3, 3]) torch.Size([64, 64, 3, 3])
torch.Size([128]) torch.Size([64])
torch.Size([128]) torch.Size([64])
torch.Size([128, 64, 1, 1]) torch.Size([64])
torch.Size([128]) torch.Size([64])
torch.Size([128]) torch.Size([])
torch.Size([128, 128, 3, 3]) torch.Size([64, 64, 3, 3])
torch.Si

In [63]:
o = th.optim.Adam(m.parameters())

In [73]:
from mutil.pickle import *

In [84]:
th.save(list(o.state_dict()['state'].values()), 'tmp.pt')

In [83]:
list(o.state_dict()['param_groups'][0].values())

[0.001,
 (0.9, 0.999),
 1e-08,
 0,
 False,
 [139724354188704,
  139724349412288,
  139724349412368,
  139724349412928,
  139724349412848,
  139724349413088,
  139724349413488,
  139724349413408,
  139724349413648,
  139724349414208,
  139724349414448,
  139724349414528,
  139724349476944,
  139724349477184,
  139724349477264,
  139724349477744,
  139724349477584,
  139724349477904,
  139724349478704,
  139724349478624,
  139724349478864,
  139724349398704,
  139724349398784,
  139724349398544,
  139724349479584,
  139724349479504,
  139724349479744,
  139724349480544,
  139724349480784,
  139724349480864,
  139724349528096,
  139724349528336,
  139724349528416,
  139724349529296,
  139724349529536,
  139724349529616,
  139724349526736,
  139724349526976,
  139724349527056,
  139724345266656,
  139724345266896,
  139724345266976,
  139724345267856,
  139724345268096,
  139724345268176,
  139724345311312,
  139724345311552,
  139724345311632,
  139724345312512,
  139724345312752,
  13972

In [42]:
%%time
th.save(m.state_dict(), "mnist_cnn.pt")
m.load_state_dict(th.load("mnist_cnn.pt"))

CPU times: user 34.2 ms, sys: 57.2 ms, total: 91.4 ms
Wall time: 69 ms


<All keys matched successfully>

In [43]:
%%time
for i in range(10):
    th.save(m.state_dict(), "mnist_cnn.pt")

CPU times: user 47.5 ms, sys: 467 ms, total: 514 ms
Wall time: 3.76 s


In [35]:
%%timeit
m.load_state_dict(th.load("mnist_cnn.pt"))

24.2 ms ± 418 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [52]:
opt = th.load('../tmp/460_opt.pt')

In [53]:
print(opt)

[]


In [56]:
from syftutils.multipointer import (
    avg_model_state_dicts,
    commulative_avg_model_state_dicts,
)

In [61]:
%%timeit
r = commulative_avg_model_state_dicts(m.state_dict(),m.state_dict(),1)

31.6 ms ± 1.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
